# vector arithmetic
- unlike languages like Matlab, Mathematica and C++, Python does not provide
vector 'arithmetic', which is extremely useful in:
    - machine learning
    - statistics 
    - big data
    - parallel processing
    - science and engineering in general


In [ ]:
# first time i tried this i was surprised
# expected to get [3,6,9]

[1,2,3]*3

In [ ]:
# this doesn't work at all,
# i expected [4,10,18]

[1,2,3]*[4,5,6]

In [ ]:
# this doesn't work either

import math

math.sin([1.,2.,3.])

In [ ]:
# more concatenating
# expected [5,7,9]

[1,2,3]+[4,5,6]

# numpy - numerical python
- almost all python packages and people dealing with non trivial amounts of data use numpy arrays
- much more time and space efficient than python lists 
- provides vector arithmetic
- many convenient methods for modifiying arrays
- usually elements of a numpy array are all the same type
- array elements are "unboxed"
- array indexing techniques are almost identical to Matlab, but:
    - Python 1st index is 0
    - Matlab 1st index is 1


In [3]:
# numpy is included in the Anaconda distribution

# standard import form for numpy 

import numpy as np


In [5]:
# note a.nbytes = 24 = 3 * 8
# no per float overhead

a= np.array([1.,2.,3.])
b= np.array([4.,5.,6.])
[a, type(a), a.size, a.shape, a.itemsize, a.dtype, a.nbytes]

[array([ 1.,  2.,  3.]), numpy.ndarray, 3, (3,), 8, dtype('float64'), 24]

In [6]:
a

array([ 1.,  2.,  3.])

In [7]:
b

array([ 4.,  5.,  6.])

In [8]:
# vector arithmetic - numpy objects define __add__, __mul__, etc

[a + b, a-b, a*b, b/a, a+10, a*10, a.min(), a.max(), a.mean(), a.dot(b)]

[array([ 5.,  7.,  9.]),
 array([-3., -3., -3.]),
 array([  4.,  10.,  18.]),
 array([ 4. ,  2.5,  2. ]),
 array([ 11.,  12.,  13.]),
 array([ 10.,  20.,  30.]),
 1.0,
 3.0,
 2.0,
 32.0]

In [7]:
# convert a array of meters into feet

np.array([2.3, 5.1, 8.7, 1.2]) * 3

array([  6.9,  15.3,  26.1,   3.6])

In [8]:
# vector functions
# using sin from numpy module, NOT math module
# np.sin acts on each element of a numpy array, and returns a new array

ls=np.linspace(0, 6.28, 10)
[ls, np.sin(ls)]

[array([ 0.        ,  0.69777778,  1.39555556,  2.09333333,  2.79111111,
         3.48888889,  4.18666667,  4.88444444,  5.58222222,  6.28      ]),
 array([ 0.        ,  0.64251645,  0.98468459,  0.8665558 ,  0.34335012,
        -0.34035671, -0.86496168, -0.98523494, -0.644954  , -0.0031853 ])]

In [9]:
# make arrays

a = np.array([1,2,3])
b = np.array([[1,2],[3,4]])
[a, type(a),b]

[array([1, 2, 3]), numpy.ndarray, array([[1, 2],
        [3, 4]])]

In [10]:
# copy an array 

d = b.copy()
e = b.copy()

[b, d, b is d]

[array([[1, 2],
        [3, 4]]), array([[1, 2],
        [3, 4]]), False]

In [11]:
# element by element compare

d[1,1] = 40

b == d


array([[ True,  True],
       [ True, False]], dtype=bool)

In [12]:
# compare all elements

[np.array_equal(b, d), np.array_equal(b, e)]

[False, True]

In [9]:
# make a square matrix

def sqmat(n):
    # make 1D matrix
    a=np.array(range(n*n))
    # reshape to 2D
    s = a.reshape(n,n)
    return(s)

sm = sqmat(4)
sm

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
# Any difference?

[sm[3][2], sm[3,2]]

[14, 14]

In [14]:
sqmat(4).transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [40]:
# can 'rotate' array

np.rot90(sqmat(4))

array([[ 3,  7, 11, 15],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13],
       [ 0,  4,  8, 12]])

In [15]:
# other ways to make matrix
# familiar from matlab

zs = np.zeros((3,3))
zs

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
zs[1,1] = 1
zs

array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

In [17]:
np.ones((2,2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [18]:
# 2d slices

f = sqmat(5)
f

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
# pull out a sub matrix

f[2:4, 2:]

array([[12, 13, 14],
       [17, 18, 19]])

In [20]:
# iterate by row

for r in f:
    print(r)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [21]:
# iterate by element

for e in f.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


# Reshaping arrays
- often very useful to change the 'view' or 'interpretation' of an array


In [22]:
a = np.array(range(12))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
b = a.reshape((4,3))
c = a.reshape((2,6))
b

array([[55,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
c

array([[55,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [25]:
# not the same object

[a is b , a is c]

[False, False]

In [26]:
# but...

a[0] = 55
a

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
b

array([[55,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
# a,b,c are looking at the SAME chunk of data
# so reshape is a cheap operation - it doesn't copy the data

c

array([[55,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [31]:
# the transpose is being done by swapping indexes,
# not by moving data

b.transpose()

array([[55,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [32]:
# raw data is unchanged by transpose

a

array([55,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
c

array([[55,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [31]:
a = sqmat(3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# aggregate methods

In [33]:
# sum all the elements

a.sum()

36

In [34]:
# sum columns

a.sum(axis = 0)

array([ 9, 12, 15])

In [35]:
# sum rows

a.sum(axis = 1)

array([ 3, 12, 21])

In [36]:
a.argmax()

8

In [37]:
a.mean()

4.0

In [38]:
a.std()

2.5819888974716112

# Joining arrays

In [ ]:
f

In [ ]:
np.vstack((f,f))

In [ ]:
np.hstack((f,f))

# Spliting arrays

In [ ]:
g = sqmat(3)
g

In [ ]:
# split into column arrays

np.hsplit(g,3)

In [ ]:
# split into row arrays

np.vsplit(g, 3)

In [ ]:
# range only accepts ints

range(5.8, 10.2)

In [ ]:
# arange takes floats and makes a numpy array

m = np.array(np.arange(5.7,1,-.7))
m

In [ ]:
# list index

m[ [1, 3, 2] ]

# boolean arrays

In [42]:
a = sqmat(3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
# make a boolean array

b = a > 4
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [45]:
# when a boolean array is used as an index,
# the array elements at the same position 
# as True elements are placed in a 1D array


a[b]

array([5, 6, 7, 8])

In [46]:
# 'all' ANDs together all the array elements

b.all()

False

In [47]:
# 'any' ORs together all the array elements

b.any()

True

# storing/loading arrays to/from files
- lots of ways to do this
- there are also binary formats
- [savetxt doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html)
- [genfromtxt doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html)

In [2]:
import tempfile

path = tempfile.NamedTemporaryFile().name
path


'/var/folders/7p/8hg8wwy575z8m7n_bc4mjsdc0000gn/T/tmp3xow0gnm'

In [12]:
a5 = sqmat(5)
a5
a5.dtype

dtype('int64')

In [16]:
# save ints in CSV format

np.savetxt(path, a5, fmt='%i', delimiter=',')

In [29]:
# could read it in like this

with open(path) as f:
    rows = []
    for line in f:
        # get list of strings
        row = line.split(',')
        # convert strings into ints
        rows.append(list(map(int, row)))
    print(rows)
    ra = np.array(rows)

ra

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
# this is much better

np.genfromtxt(path, delimiter=',', dtype='int64')

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Numpy also has a 'matrix' type, in the linear algebra sense
- many functions available
    - inverse
    - equation solving
    - eigenvalues and eigenvectors

In [21]:
a = np.mat("2 4 6;4 2 6;10 -4 18")
a

matrix([[ 2,  4,  6],
        [ 4,  2,  6],
        [10, -4, 18]])

In [22]:
ai = np.linalg.inv(a)
ai

matrix([[-0.41666667,  0.66666667, -0.08333333],
        [ 0.08333333,  0.16666667, -0.08333333],
        [ 0.25      , -0.33333333,  0.08333333]])

In [23]:
im = ai * a
im

matrix([[  1.00000000e+00,   1.11022302e-16,  -2.22044605e-16],
        [ -2.22044605e-16,   1.00000000e+00,  -2.22044605e-16],
        [  0.00000000e+00,   5.55111512e-17,   1.00000000e+00]])

In [24]:
im.shape


(3, 3)

In [25]:
# clean up floating point noise

import math

for row in range(im.shape[0]):
    for col in range(im.shape[1]):
        if math.fabs(im[row,col]) < .00001:
            im[row, col] = 0.0
im

matrix([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]])

# Example - Magic Squares
- a magic square is a 2D square array where all the rows, columns, and both diagonals sum to the same number
- write function 'magic' 
    - if arg is not a 2D square numpy array, raise appropriate errors
    - if arg is not a magic square, return false
    - if arg is a magic square, return the sum
    - don't use any explicit loops

In [4]:
def magic(a):
    # check we have a legitimate arg
    if not isinstance(a, np.ndarray):
        raise ValueError('not an array')
    shape = a.shape
    if not 2 == len(shape):
        raise ValueError('not a 2D array')
    if not shape[0]==shape[1]:
        raise ValueError('not square')

    # ok, we have a 2D square array
    side = shape[0]
    
    #  1D array, len = side, of column sums
    colsums = a.sum(axis=0)
    # every sum has to be equal to this one
    sum = colsums[0]
    
    # make 1D, len = side, BOOLEAN array
    # contents of array will be sum == colsum[0], sum == colsum[1]...
    colbools = sum == colsums
    # ok only if each bool is True
    if not colbools.all():
        return False
    
    # check row sums
    rowsums = a.sum(axis=1)
    rowbools = sum == rowsums
    if not rowbools.all():
        return False
    
    # True on major diagonal, other elements False
    boolmajor = np.identity(side, dtype=bool)
    # pull the elements of 'a' corresponding to True
    # in a 1D array
    majordiag = a[boolmajor]
    if sum != majordiag.sum():
        return False

    # check minor diagonal
    boolminor = np.rot90(boolmajor)
    minordiag = a[boolminor]
    if sum != minordiag.sum():
        return False

    # everything worked!
    return True
    

In [5]:
a=m.sum(axis=0)
bm = a == 21
bm
bm.all()
a

NameError: name 'm' is not defined

In [6]:
# check data type

magic([2,3,4])

ValueError: not an array

In [7]:
# check for 2D

magic(np.array([4,5]))

ValueError: not a 2D array

In [8]:
m = np.array([[3, 11,  6],
             [ 9,  7,  5],
             [ 8,  3, 10]])

magic(m)

False

In [9]:
# fix it

m[0,0] = 4
m

array([[ 4, 11,  6],
       [ 9,  7,  5],
       [ 8,  3, 10]])

In [10]:
magic(m)

True

# Ramanujan created a super magic square. 
- The top row is his birthdate (December 22, 1887). 
- Not only do the rows, columns, and diagonals add up to 139, but also:
    - A) the four corners
    - B) the four middle elements (17, 9, 24, 89), 
    - C) the first and last rows two middle numbers (12, 18, 86, 23), 
    - D) the first and last columns two middle numbers (88, 10, 25, 16)  

In [11]:
m = np.array([22,12,18,87,88,17,9,25,10,24,89,16,19,86,23,11])
m = m.reshape((4,4))
m

array([[22, 12, 18, 87],
       [88, 17,  9, 25],
       [10, 24, 89, 16],
       [19, 86, 23, 11]])

In [12]:
magic(m)

True

In [13]:
# A)

corn = m[0:5:3, 0:5:3]
corn

array([[22, 87],
       [19, 11]])

In [14]:
corn.sum()

139

In [15]:
# B)

mid = m[1:3,1:3]
mid

array([[17,  9],
       [24, 89]])

In [16]:
mid.sum()

139

In [17]:
m

array([[22, 12, 18, 87],
       [88, 17,  9, 25],
       [10, 24, 89, 16],
       [19, 86, 23, 11]])

In [18]:
# C)

c = m[0:4:3, 1:3]
c

array([[12, 18],
       [86, 23]])

In [19]:
c.sum()

139

In [20]:
# D)

d = m[1:3, 0:4:3]
d

array([[88, 25],
       [10, 16]])

In [21]:
d.sum()

139